version: "3.9"
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16  # Specify the desired subnet
          gateway: 172.18.0.1   # Specify the desired gateway IP
          ip_range: 172.18.0.2/32
services:
  stockage:
    build:
      context: ./backend/service_stockage/
    ports:
      - 5000:5000
    networks:
      - network
  conversion:
    build: 
      context: ./backend/service_conversion/
    ports:
      - 5001:5001
    networks:
      - network
  registry:
    build: 
      context: ./backend/service_register/
    ports:
      - 5005:5005
    networks:
      - network
  header:
    build: 
      context: ./backend/service_header/
    ports:
      - 5006:5006
    networks:
      - network
  rapport:
    build: 
      context: ./backend/service_rapport/
    ports:
      - 5007:5007
    networks:
      - network
  frontend:
    build:
      context: ./frontend/
    command: npm run serve
    ports:
      - 3000:3000
  nifi:
    image: apache/nifi:latest
    build : ./nifi
    ports:
      - 8443:8443
      - 5003:5003
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=6fce31dc-a3ef-4aba-94fc-535d43cca842
      - SINGLE_USER_CREDENTIALS_PASSWORD=qDNgACY9tCsBUUVkQTGdRUKlSHQZfdcM
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data
    networks:
      network:
        ipv4_address: 172.18.0.2  # Specify the desired static IP address
    
